### ISSUE TITLE
Is it possible to use this library with 433mhz radio receiver

### ISSUE THREAD

**Issue by venil7** [rahul-thakoor/rust_gpiozero#6]
something as simple as a function gets called when 433mhz receiver receives a signal

**Comment by rahul-thakoor** [comment]
Hey there! I'm not entirely sure if this will work, but you could try the following:

1. connect your 433Mhz Rx module to the RPi. 
2. Configure the 'data' pin as a digital input pin
  [DigitalInputDevice](https://docs.rs/rust_gpiozero/0.2.0/rust_gpiozero/input_devices/struct.DigitalInputDevice.html) 
3. Read the pin value over time, transcribe the signal and call the appropriate function
    [Tutorial explaining how to use 433 modules](https://www.instructables.com/id/Super-Simple-Raspberry-Pi-433MHz-Home-Automation/)

Hope this helps,
Let me know how it turns out. I'm curious too.
Thanks
